# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(802, 697)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.TabbedLayout = QtGui.QTabWidget(self.centralwidget)
        self.TabbedLayout.setGeometry(QtCore.QRect(0, 130, 801, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabbedLayout.sizePolicy().hasHeightForWidth())
        self.TabbedLayout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.TabbedLayout.setFont(font)
        self.TabbedLayout.setTabShape(QtGui.QTabWidget.Rounded)
        self.TabbedLayout.setObjectName(_fromUtf8("TabbedLayout"))
        self.tabCoreDetails = QtGui.QWidget()
        self.tabCoreDetails.setObjectName(_fromUtf8("tabCoreDetails"))
        self.frameHeroDetails = QtGui.QFrame(self.tabCoreDetails)
        self.frameHeroDetails.setGeometry(QtCore.QRect(10, 70, 421, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frameHeroDetails.setFont(font)
        self.frameHeroDetails.setFrameShape(QtGui.QFrame.Box)
        self.frameHeroDetails.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHeroDetails.setObjectName(_fromUtf8("frameHeroDetails"))
        self.lblHeroesName = QtGui.QLabel(self.frameHeroDetails)
        self.lblHeroesName.setGeometry(QtCore.QRect(10, 20, 91, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeroesName.setFont(font)
        self.lblHeroesName.setObjectName(_fromUtf8("lblHeroesName"))
        self.txtHeroesName = QtGui.QPlainTextEdit(self.frameHeroDetails)
        self.txtHeroesName.setGeometry(QtCore.QRect(100, 10, 311, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtHeroesName.setFont(font)
        self.txtHeroesName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtHeroesName.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtHeroesName.setObjectName(_fromUtf8("txtHeroesName"))
        self.checkBoxOP = QtGui.QCheckBox(self.frameHeroDetails)
        self.checkBoxOP.setGeometry(QtCore.QRect(110, 90, 88, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.checkBoxOP.setFont(font)
        self.checkBoxOP.setObjectName(_fromUtf8("checkBoxOP"))
        self.lblOP = QtGui.QLabel(self.frameHeroDetails)
        self.lblOP.setGeometry(QtCore.QRect(10, 90, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblOP.setFont(font)
        self.lblOP.setObjectName(_fromUtf8("lblOP"))
        self.lblSpeech = QtGui.QLabel(self.frameHeroDetails)
        self.lblSpeech.setGeometry(QtCore.QRect(10, 130, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblSpeech.setFont(font)
        self.lblSpeech.setObjectName(_fromUtf8("lblSpeech"))
        self.txtSpeech = QtGui.QPlainTextEdit(self.frameHeroDetails)
        self.txtSpeech.setGeometry(QtCore.QRect(110, 120, 301, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtSpeech.setFont(font)
        self.txtSpeech.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSpeech.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtSpeech.setObjectName(_fromUtf8("txtSpeech"))
        self.lblFancyName = QtGui.QLabel(self.frameHeroDetails)
        self.lblFancyName.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblFancyName.setFont(font)
        self.lblFancyName.setWordWrap(True)
        self.lblFancyName.setObjectName(_fromUtf8("lblFancyName"))
        self.txtHeroesFancyName = QtGui.QPlainTextEdit(self.frameHeroDetails)
        self.txtHeroesFancyName.setGeometry(QtCore.QRect(140, 50, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtHeroesFancyName.setFont(font)
        self.txtHeroesFancyName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtHeroesFancyName.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtHeroesFancyName.setObjectName(_fromUtf8("txtHeroesFancyName"))
        self.txtChatColor = QtGui.QPlainTextEdit(self.frameHeroDetails)
        self.txtChatColor.setGeometry(QtCore.QRect(110, 160, 301, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtChatColor.setFont(font)
        self.txtChatColor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChatColor.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtChatColor.setObjectName(_fromUtf8("txtChatColor"))
        self.lblChatColor = QtGui.QLabel(self.frameHeroDetails)
        self.lblChatColor.setGeometry(QtCore.QRect(10, 170, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblChatColor.setFont(font)
        self.lblChatColor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblChatColor.setWordWrap(True)
        self.lblChatColor.setObjectName(_fromUtf8("lblChatColor"))
        self.frame = QtGui.QFrame(self.tabCoreDetails)
        self.frame.setGeometry(QtCore.QRect(10, 290, 421, 151))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lblTrails = QtGui.QLabel(self.frame)
        self.lblTrails.setGeometry(QtCore.QRect(10, 10, 51, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblTrails.setFont(font)
        self.lblTrails.setObjectName(_fromUtf8("lblTrails"))
        self.listTrails = QtGui.QListWidget(self.frame)
        self.listTrails.setGeometry(QtCore.QRect(10, 30, 401, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listTrails.setFont(font)
        self.listTrails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listTrails.setAlternatingRowColors(True)
        self.listTrails.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listTrails.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listTrails.setObjectName(_fromUtf8("listTrails"))
        self.lblOptional = QtGui.QLabel(self.frame)
        self.lblOptional.setGeometry(QtCore.QRect(70, 10, 181, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.lblOptional.setFont(font)
        self.lblOptional.setObjectName(_fromUtf8("lblOptional"))
        self.framePowers = QtGui.QFrame(self.tabCoreDetails)
        self.framePowers.setGeometry(QtCore.QRect(440, 10, 351, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.framePowers.setFont(font)
        self.framePowers.setFrameShape(QtGui.QFrame.Panel)
        self.framePowers.setFrameShadow(QtGui.QFrame.Raised)
        self.framePowers.setObjectName(_fromUtf8("framePowers"))
        self.lblPowers = QtGui.QLabel(self.framePowers)
        self.lblPowers.setGeometry(QtCore.QRect(10, 10, 111, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblPowers.setFont(font)
        self.lblPowers.setObjectName(_fromUtf8("lblPowers"))
        self.txtPowers = QtGui.QPlainTextEdit(self.framePowers)
        self.txtPowers.setGeometry(QtCore.QRect(10, 30, 331, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtPowers.setFont(font)
        self.txtPowers.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtPowers.setBackgroundVisible(False)
        self.txtPowers.setObjectName(_fromUtf8("txtPowers"))
        self.btnLoadPowersExample = QtGui.QPushButton(self.framePowers)
        self.btnLoadPowersExample.setGeometry(QtCore.QRect(130, 160, 101, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnLoadPowersExample.setFont(font)
        self.btnLoadPowersExample.setObjectName(_fromUtf8("btnLoadPowersExample"))
        self.frameBuffs = QtGui.QFrame(self.tabCoreDetails)
        self.frameBuffs.setGeometry(QtCore.QRect(440, 210, 351, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frameBuffs.setFont(font)
        self.frameBuffs.setFrameShape(QtGui.QFrame.Panel)
        self.frameBuffs.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBuffs.setObjectName(_fromUtf8("frameBuffs"))
        self.lblBuffs = QtGui.QLabel(self.frameBuffs)
        self.lblBuffs.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblBuffs.setFont(font)
        self.lblBuffs.setObjectName(_fromUtf8("lblBuffs"))
        self.txtBuffs = QtGui.QPlainTextEdit(self.frameBuffs)
        self.txtBuffs.setGeometry(QtCore.QRect(10, 30, 331, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtBuffs.setFont(font)
        self.txtBuffs.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtBuffs.setObjectName(_fromUtf8("txtBuffs"))
        self.btnLoadBuffsExample = QtGui.QPushButton(self.frameBuffs)
        self.btnLoadBuffsExample.setGeometry(QtCore.QRect(130, 200, 101, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnLoadBuffsExample.setFont(font)
        self.btnLoadBuffsExample.setObjectName(_fromUtf8("btnLoadBuffsExample"))
        self.iconSmile = QtGui.QLabel(self.tabCoreDetails)
        self.iconSmile.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.iconSmile.setText(_fromUtf8(""))
        self.iconSmile.setPixmap(QtGui.QPixmap(_fromUtf8("images/happy.png")))
        self.iconSmile.setObjectName(_fromUtf8("iconSmile"))
        self.lblYourHero = QtGui.QLabel(self.tabCoreDetails)
        self.lblYourHero.setGeometry(QtCore.QRect(60, 20, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lblYourHero.setFont(font)
        self.lblYourHero.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYourHero.setObjectName(_fromUtf8("lblYourHero"))
        self.TabbedLayout.addTab(self.tabCoreDetails, _fromUtf8(""))
        self.tabPlayerDetails = QtGui.QWidget()
        self.tabPlayerDetails.setObjectName(_fromUtf8("tabPlayerDetails"))
        self.framePlayerName = QtGui.QFrame(self.tabPlayerDetails)
        self.framePlayerName.setGeometry(QtCore.QRect(40, 20, 461, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.framePlayerName.setFont(font)
        self.framePlayerName.setFrameShape(QtGui.QFrame.Box)
        self.framePlayerName.setFrameShadow(QtGui.QFrame.Raised)
        self.framePlayerName.setObjectName(_fromUtf8("framePlayerName"))
        self.lblPlayerName = QtGui.QLabel(self.framePlayerName)
        self.lblPlayerName.setGeometry(QtCore.QRect(10, 10, 161, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblPlayerName.setFont(font)
        self.lblPlayerName.setScaledContents(False)
        self.lblPlayerName.setObjectName(_fromUtf8("lblPlayerName"))
        self.txtPlayerName = QtGui.QPlainTextEdit(self.framePlayerName)
        self.txtPlayerName.setGeometry(QtCore.QRect(170, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtPlayerName.setFont(font)
        self.txtPlayerName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPlayerName.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtPlayerName.setObjectName(_fromUtf8("txtPlayerName"))
        self.btnUsePlayerName = QtGui.QPushButton(self.framePlayerName)
        self.btnUsePlayerName.setGeometry(QtCore.QRect(380, 10, 71, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnUsePlayerName.setFont(font)
        self.btnUsePlayerName.setObjectName(_fromUtf8("btnUsePlayerName"))
        self.frame_2 = QtGui.QFrame(self.tabPlayerDetails)
        self.frame_2.setGeometry(QtCore.QRect(40, 80, 751, 371))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.txtInfoPlayerName = QtGui.QPlainTextEdit(self.frame_2)
        self.txtInfoPlayerName.setGeometry(QtCore.QRect(130, 10, 211, 31))
        self.txtInfoPlayerName.setFrameShape(QtGui.QFrame.Box)
        self.txtInfoPlayerName.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtInfoPlayerName.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtInfoPlayerName.setObjectName(_fromUtf8("txtInfoPlayerName"))
        self.lblInfoPlayerName = QtGui.QLabel(self.frame_2)
        self.lblInfoPlayerName.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfoPlayerName.setFont(font)
        self.lblInfoPlayerName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblInfoPlayerName.setObjectName(_fromUtf8("lblInfoPlayerName"))
        self.txtInfoSignature = QtGui.QPlainTextEdit(self.frame_2)
        self.txtInfoSignature.setGeometry(QtCore.QRect(130, 90, 611, 121))
        self.txtInfoSignature.setFrameShape(QtGui.QFrame.Box)
        self.txtInfoSignature.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtInfoSignature.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtInfoSignature.setObjectName(_fromUtf8("txtInfoSignature"))
        self.lblInfoSignature = QtGui.QLabel(self.frame_2)
        self.lblInfoSignature.setGeometry(QtCore.QRect(10, 90, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfoSignature.setFont(font)
        self.lblInfoSignature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblInfoSignature.setObjectName(_fromUtf8("lblInfoSignature"))
        self.lblInfoUUID = QtGui.QLabel(self.frame_2)
        self.lblInfoUUID.setGeometry(QtCore.QRect(30, 50, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfoUUID.setFont(font)
        self.lblInfoUUID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblInfoUUID.setObjectName(_fromUtf8("lblInfoUUID"))
        self.txtInfoValue = QtGui.QPlainTextEdit(self.frame_2)
        self.txtInfoValue.setGeometry(QtCore.QRect(130, 220, 611, 141))
        self.txtInfoValue.setFrameShape(QtGui.QFrame.Box)
        self.txtInfoValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtInfoValue.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtInfoValue.setObjectName(_fromUtf8("txtInfoValue"))
        self.txtInfoUUID = QtGui.QPlainTextEdit(self.frame_2)
        self.txtInfoUUID.setGeometry(QtCore.QRect(130, 50, 611, 31))
        self.txtInfoUUID.setFrameShape(QtGui.QFrame.Box)
        self.txtInfoUUID.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtInfoUUID.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtInfoUUID.setObjectName(_fromUtf8("txtInfoUUID"))
        self.lblInfoValue = QtGui.QLabel(self.frame_2)
        self.lblInfoValue.setGeometry(QtCore.QRect(10, 220, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblInfoValue.setFont(font)
        self.lblInfoValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblInfoValue.setObjectName(_fromUtf8("lblInfoValue"))
        self.TabbedLayout.addTab(self.tabPlayerDetails, _fromUtf8(""))
        self.tabColorCodes = QtGui.QWidget()
        self.tabColorCodes.setObjectName(_fromUtf8("tabColorCodes"))
        self.frameColorCodes = QtGui.QFrame(self.tabColorCodes)
        self.frameColorCodes.setGeometry(QtCore.QRect(10, 10, 461, 351))
        self.frameColorCodes.setFrameShape(QtGui.QFrame.Box)
        self.frameColorCodes.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameColorCodes.setObjectName(_fromUtf8("frameColorCodes"))
        self.lblColorCodes = QtGui.QLabel(self.frameColorCodes)
        self.lblColorCodes.setGeometry(QtCore.QRect(10, 0, 431, 351))
        self.lblColorCodes.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblColorCodes.setText(_fromUtf8(""))
        self.lblColorCodes.setPixmap(QtGui.QPixmap(_fromUtf8("images/colorcodes.jpg")))
        self.lblColorCodes.setObjectName(_fromUtf8("lblColorCodes"))
        self.btnColor_1 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_1.setGeometry(QtCore.QRect(430, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnColor_1.setFont(font)
        self.btnColor_1.setText(_fromUtf8(""))
        self.btnColor_1.setObjectName(_fromUtf8("btnColor_1"))
        self.btnColor_2 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_2.setGeometry(QtCore.QRect(430, 40, 21, 16))
        self.btnColor_2.setText(_fromUtf8(""))
        self.btnColor_2.setObjectName(_fromUtf8("btnColor_2"))
        self.btnColor_3 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_3.setGeometry(QtCore.QRect(430, 60, 21, 16))
        self.btnColor_3.setText(_fromUtf8(""))
        self.btnColor_3.setObjectName(_fromUtf8("btnColor_3"))
        self.btnColor_4 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_4.setGeometry(QtCore.QRect(430, 80, 21, 16))
        self.btnColor_4.setText(_fromUtf8(""))
        self.btnColor_4.setObjectName(_fromUtf8("btnColor_4"))
        self.btnColor_5 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_5.setGeometry(QtCore.QRect(430, 100, 21, 16))
        self.btnColor_5.setText(_fromUtf8(""))
        self.btnColor_5.setObjectName(_fromUtf8("btnColor_5"))
        self.btnColor_6 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_6.setGeometry(QtCore.QRect(430, 120, 21, 16))
        self.btnColor_6.setText(_fromUtf8(""))
        self.btnColor_6.setObjectName(_fromUtf8("btnColor_6"))
        self.btnColor_7 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_7.setGeometry(QtCore.QRect(430, 140, 21, 16))
        self.btnColor_7.setText(_fromUtf8(""))
        self.btnColor_7.setObjectName(_fromUtf8("btnColor_7"))
        self.btnColor_8 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_8.setGeometry(QtCore.QRect(430, 160, 21, 16))
        self.btnColor_8.setText(_fromUtf8(""))
        self.btnColor_8.setObjectName(_fromUtf8("btnColor_8"))
        self.btnColor_9 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_9.setGeometry(QtCore.QRect(430, 180, 21, 16))
        self.btnColor_9.setText(_fromUtf8(""))
        self.btnColor_9.setObjectName(_fromUtf8("btnColor_9"))
        self.btnColor_10 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_10.setGeometry(QtCore.QRect(430, 200, 21, 16))
        self.btnColor_10.setText(_fromUtf8(""))
        self.btnColor_10.setObjectName(_fromUtf8("btnColor_10"))
        self.btnColor_11 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_11.setGeometry(QtCore.QRect(430, 220, 21, 16))
        self.btnColor_11.setText(_fromUtf8(""))
        self.btnColor_11.setObjectName(_fromUtf8("btnColor_11"))
        self.btnColor_12 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_12.setGeometry(QtCore.QRect(430, 240, 21, 16))
        self.btnColor_12.setText(_fromUtf8(""))
        self.btnColor_12.setObjectName(_fromUtf8("btnColor_12"))
        self.btnColor_13 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_13.setGeometry(QtCore.QRect(430, 260, 21, 16))
        self.btnColor_13.setText(_fromUtf8(""))
        self.btnColor_13.setObjectName(_fromUtf8("btnColor_13"))
        self.btnColor_14 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_14.setGeometry(QtCore.QRect(430, 280, 21, 16))
        self.btnColor_14.setText(_fromUtf8(""))
        self.btnColor_14.setObjectName(_fromUtf8("btnColor_14"))
        self.btnColor_15 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_15.setGeometry(QtCore.QRect(430, 300, 21, 16))
        self.btnColor_15.setText(_fromUtf8(""))
        self.btnColor_15.setObjectName(_fromUtf8("btnColor_15"))
        self.btnColor_16 = QtGui.QPushButton(self.frameColorCodes)
        self.btnColor_16.setGeometry(QtCore.QRect(430, 320, 21, 16))
        self.btnColor_16.setText(_fromUtf8(""))
        self.btnColor_16.setObjectName(_fromUtf8("btnColor_16"))
        self.lblColorCodes1 = QtGui.QFrame(self.tabColorCodes)
        self.lblColorCodes1.setGeometry(QtCore.QRect(480, 10, 301, 171))
        self.lblColorCodes1.setFrameShape(QtGui.QFrame.Box)
        self.lblColorCodes1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblColorCodes1.setObjectName(_fromUtf8("lblColorCodes1"))
        self.lblBukkitCodeK = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeK.setGeometry(QtCore.QRect(100, 10, 121, 17))
        self.lblBukkitCodeK.setObjectName(_fromUtf8("lblBukkitCodeK"))
        self.lblBukkitCodeL = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeL.setGeometry(QtCore.QRect(100, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.lblBukkitCodeL.setFont(font)
        self.lblBukkitCodeL.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblBukkitCodeL.setFrameShadow(QtGui.QFrame.Plain)
        self.lblBukkitCodeL.setTextFormat(QtCore.Qt.AutoText)
        self.lblBukkitCodeL.setObjectName(_fromUtf8("lblBukkitCodeL"))
        self.lblBukkitCodeM = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeM.setGeometry(QtCore.QRect(100, 50, 131, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setStrikeOut(True)
        self.lblBukkitCodeM.setFont(font)
        self.lblBukkitCodeM.setObjectName(_fromUtf8("lblBukkitCodeM"))
        self.lblBukkitCodeN = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeN.setGeometry(QtCore.QRect(100, 70, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setUnderline(True)
        self.lblBukkitCodeN.setFont(font)
        self.lblBukkitCodeN.setObjectName(_fromUtf8("lblBukkitCodeN"))
        self.lblBukkitCodeO = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeO.setGeometry(QtCore.QRect(100, 90, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setItalic(True)
        self.lblBukkitCodeO.setFont(font)
        self.lblBukkitCodeO.setObjectName(_fromUtf8("lblBukkitCodeO"))
        self.lblBukkitCodeR = QtGui.QLabel(self.lblColorCodes1)
        self.lblBukkitCodeR.setGeometry(QtCore.QRect(100, 140, 121, 17))
        self.lblBukkitCodeR.setObjectName(_fromUtf8("lblBukkitCodeR"))
        self.btnColor_17 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_17.setGeometry(QtCore.QRect(230, 10, 21, 16))
        self.btnColor_17.setText(_fromUtf8(""))
        self.btnColor_17.setObjectName(_fromUtf8("btnColor_17"))
        self.btnColor_18 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_18.setGeometry(QtCore.QRect(230, 30, 21, 16))
        self.btnColor_18.setText(_fromUtf8(""))
        self.btnColor_18.setObjectName(_fromUtf8("btnColor_18"))
        self.btnColor_19 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_19.setGeometry(QtCore.QRect(230, 50, 21, 16))
        self.btnColor_19.setText(_fromUtf8(""))
        self.btnColor_19.setObjectName(_fromUtf8("btnColor_19"))
        self.btnColor_20 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_20.setGeometry(QtCore.QRect(230, 70, 21, 16))
        self.btnColor_20.setText(_fromUtf8(""))
        self.btnColor_20.setObjectName(_fromUtf8("btnColor_20"))
        self.btnColor_21 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_21.setGeometry(QtCore.QRect(230, 90, 21, 16))
        self.btnColor_21.setText(_fromUtf8(""))
        self.btnColor_21.setObjectName(_fromUtf8("btnColor_21"))
        self.btnColor_22 = QtGui.QPushButton(self.lblColorCodes1)
        self.btnColor_22.setGeometry(QtCore.QRect(230, 140, 21, 16))
        self.btnColor_22.setText(_fromUtf8(""))
        self.btnColor_22.setObjectName(_fromUtf8("btnColor_22"))
        self.frameScratchPad = QtGui.QFrame(self.tabColorCodes)
        self.frameScratchPad.setGeometry(QtCore.QRect(10, 370, 781, 81))
        self.frameScratchPad.setFrameShape(QtGui.QFrame.Box)
        self.frameScratchPad.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameScratchPad.setObjectName(_fromUtf8("frameScratchPad"))
        self.txtScratchPad = QtGui.QPlainTextEdit(self.frameScratchPad)
        self.txtScratchPad.setGeometry(QtCore.QRect(10, 40, 761, 31))
        self.txtScratchPad.setAutoFillBackground(False)
        self.txtScratchPad.setFrameShape(QtGui.QFrame.Box)
        self.txtScratchPad.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtScratchPad.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtScratchPad.setObjectName(_fromUtf8("txtScratchPad"))
        self.lblScratchPad = QtGui.QLabel(self.frameScratchPad)
        self.lblScratchPad.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.lblScratchPad.setObjectName(_fromUtf8("lblScratchPad"))
        self.btnCloneToHeroName = QtGui.QPushButton(self.frameScratchPad)
        self.btnCloneToHeroName.setGeometry(QtCore.QRect(90, 10, 231, 27))
        self.btnCloneToHeroName.setObjectName(_fromUtf8("btnCloneToHeroName"))
        self.btnCloneToHeroesSpeech = QtGui.QPushButton(self.frameScratchPad)
        self.btnCloneToHeroesSpeech.setGeometry(QtCore.QRect(330, 10, 171, 27))
        self.btnCloneToHeroesSpeech.setObjectName(_fromUtf8("btnCloneToHeroesSpeech"))
        self.btnClearScratchPad = QtGui.QPushButton(self.frameScratchPad)
        self.btnClearScratchPad.setGeometry(QtCore.QRect(690, 10, 81, 27))
        self.btnClearScratchPad.setObjectName(_fromUtf8("btnClearScratchPad"))
        self.btnCloneToHeroesChatColor = QtGui.QPushButton(self.frameScratchPad)
        self.btnCloneToHeroesChatColor.setGeometry(QtCore.QRect(510, 10, 171, 27))
        self.btnCloneToHeroesChatColor.setObjectName(_fromUtf8("btnCloneToHeroesChatColor"))
        self.TabbedLayout.addTab(self.tabColorCodes, _fromUtf8(""))
        self.tabPermissions = QtGui.QWidget()
        self.tabPermissions.setObjectName(_fromUtf8("tabPermissions"))
        self.txtHeroPermissions = QtGui.QPlainTextEdit(self.tabPermissions)
        self.txtHeroPermissions.setGeometry(QtCore.QRect(10, 100, 391, 311))
        self.txtHeroPermissions.setObjectName(_fromUtf8("txtHeroPermissions"))
        self.lblHeroCustomPermissions = QtGui.QLabel(self.tabPermissions)
        self.lblHeroCustomPermissions.setGeometry(QtCore.QRect(10, 10, 191, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblHeroCustomPermissions.setFont(font)
        self.lblHeroCustomPermissions.setObjectName(_fromUtf8("lblHeroCustomPermissions"))
        self.lblAvailablePermissions = QtGui.QLabel(self.tabPermissions)
        self.lblAvailablePermissions.setGeometry(QtCore.QRect(410, 10, 161, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAvailablePermissions.setFont(font)
        self.lblAvailablePermissions.setObjectName(_fromUtf8("lblAvailablePermissions"))
        self.lblCustomPermissionsHelp = QtGui.QLabel(self.tabPermissions)
        self.lblCustomPermissionsHelp.setGeometry(QtCore.QRect(10, 30, 381, 51))
        self.lblCustomPermissionsHelp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblCustomPermissionsHelp.setWordWrap(True)
        self.lblCustomPermissionsHelp.setObjectName(_fromUtf8("lblCustomPermissionsHelp"))
        self.lblAvailablePermissionsHelp = QtGui.QLabel(self.tabPermissions)
        self.lblAvailablePermissionsHelp.setGeometry(QtCore.QRect(410, 30, 371, 51))
        self.lblAvailablePermissionsHelp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblAvailablePermissionsHelp.setWordWrap(True)
        self.lblAvailablePermissionsHelp.setObjectName(_fromUtf8("lblAvailablePermissionsHelp"))
        self.lblPermissionsInfo = QtGui.QLabel(self.tabPermissions)
        self.lblPermissionsInfo.setGeometry(QtCore.QRect(10, 420, 771, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lblPermissionsInfo.setFont(font)
        self.lblPermissionsInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblPermissionsInfo.setWordWrap(True)
        self.lblPermissionsInfo.setObjectName(_fromUtf8("lblPermissionsInfo"))
        self.listPermissions = QtGui.QListWidget(self.tabPermissions)
        self.listPermissions.setGeometry(QtCore.QRect(410, 100, 371, 311))
        self.listPermissions.setAlternatingRowColors(True)
        self.listPermissions.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listPermissions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listPermissions.setObjectName(_fromUtf8("listPermissions"))
        self.TabbedLayout.addTab(self.tabPermissions, _fromUtf8(""))
        self.tabEnchantments = QtGui.QWidget()
        self.tabEnchantments.setObjectName(_fromUtf8("tabEnchantments"))
        self.listEnchantments = QtGui.QListWidget(self.tabEnchantments)
        self.listEnchantments.setGeometry(QtCore.QRect(10, 10, 781, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listEnchantments.setFont(font)
        self.listEnchantments.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listEnchantments.setAlternatingRowColors(True)
        self.listEnchantments.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listEnchantments.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listEnchantments.setObjectName(_fromUtf8("listEnchantments"))
        self.TabbedLayout.addTab(self.tabEnchantments, _fromUtf8(""))
        self.tabEffects = QtGui.QWidget()
        self.tabEffects.setObjectName(_fromUtf8("tabEffects"))
        self.listEffects = QtGui.QListWidget(self.tabEffects)
        self.listEffects.setGeometry(QtCore.QRect(10, 10, 781, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listEffects.setFont(font)
        self.listEffects.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listEffects.setAlternatingRowColors(True)
        self.listEffects.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listEffects.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listEffects.setObjectName(_fromUtf8("listEffects"))
        self.TabbedLayout.addTab(self.tabEffects, _fromUtf8(""))
        self.tabBlockIDs = QtGui.QWidget()
        self.tabBlockIDs.setObjectName(_fromUtf8("tabBlockIDs"))
        self.listBlocks = QtGui.QListWidget(self.tabBlockIDs)
        self.listBlocks.setGeometry(QtCore.QRect(10, 10, 781, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listBlocks.setFont(font)
        self.listBlocks.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listBlocks.setAlternatingRowColors(True)
        self.listBlocks.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listBlocks.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listBlocks.setObjectName(_fromUtf8("listBlocks"))
        self.TabbedLayout.addTab(self.tabBlockIDs, _fromUtf8(""))
        self.tabBuild = QtGui.QWidget()
        self.tabBuild.setObjectName(_fromUtf8("tabBuild"))
        self.picBuild = QtGui.QLabel(self.tabBuild)
        self.picBuild.setGeometry(QtCore.QRect(530, 0, 261, 291))
        self.picBuild.setText(_fromUtf8(""))
        self.picBuild.setPixmap(QtGui.QPixmap(_fromUtf8("images/build.png")))
        self.picBuild.setScaledContents(False)
        self.picBuild.setObjectName(_fromUtf8("picBuild"))
        self.btnCreate = QtGui.QPushButton(self.tabBuild)
        self.btnCreate.setGeometry(QtCore.QRect(160, 120, 261, 81))
        self.btnCreate.setObjectName(_fromUtf8("btnCreate"))
        self.TabbedLayout.addTab(self.tabBuild, _fromUtf8(""))
        self.picIcon = QtGui.QLabel(self.centralwidget)
        self.picIcon.setGeometry(QtCore.QRect(660, 0, 141, 131))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.picIcon.setFont(font)
        self.picIcon.setText(_fromUtf8(""))
        self.picIcon.setPixmap(QtGui.QPixmap(_fromUtf8("images/happy-big.png")))
        self.picIcon.setObjectName(_fromUtf8("picIcon"))
        self.lblHeroBuddy = QtGui.QLabel(self.centralwidget)
        self.lblHeroBuddy.setGeometry(QtCore.QRect(50, 20, 631, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblHeroBuddy.setFont(font)
        self.lblHeroBuddy.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeroBuddy.setObjectName(_fromUtf8("lblHeroBuddy"))
        self.listStatus = QtGui.QListWidget(self.centralwidget)
        self.listStatus.setGeometry(QtCore.QRect(5, 630, 791, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listStatus.setFont(font)
        self.listStatus.setFrameShape(QtGui.QFrame.Box)
        self.listStatus.setFrameShadow(QtGui.QFrame.Plain)
        self.listStatus.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listStatus.setAlternatingRowColors(True)
        self.listStatus.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listStatus.setObjectName(_fromUtf8("listStatus"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.TabbedLayout.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtHeroesName, self.txtHeroesFancyName)
        MainWindow.setTabOrder(self.txtHeroesFancyName, self.checkBoxOP)
        MainWindow.setTabOrder(self.checkBoxOP, self.txtSpeech)
        MainWindow.setTabOrder(self.txtSpeech, self.listTrails)
        MainWindow.setTabOrder(self.listTrails, self.txtPowers)
        MainWindow.setTabOrder(self.txtPowers, self.btnLoadPowersExample)
        MainWindow.setTabOrder(self.btnLoadPowersExample, self.txtBuffs)
        MainWindow.setTabOrder(self.txtBuffs, self.btnLoadBuffsExample)
        MainWindow.setTabOrder(self.btnLoadBuffsExample, self.txtScratchPad)
        MainWindow.setTabOrder(self.txtScratchPad, self.btnCloneToHeroName)
        MainWindow.setTabOrder(self.btnCloneToHeroName, self.btnCloneToHeroesSpeech)
        MainWindow.setTabOrder(self.btnCloneToHeroesSpeech, self.btnClearScratchPad)
        MainWindow.setTabOrder(self.btnClearScratchPad, self.listPermissions)
        MainWindow.setTabOrder(self.listPermissions, self.btnCreate)
        MainWindow.setTabOrder(self.btnCreate, self.btnColor_1)
        MainWindow.setTabOrder(self.btnColor_1, self.btnColor_2)
        MainWindow.setTabOrder(self.btnColor_2, self.btnColor_4)
        MainWindow.setTabOrder(self.btnColor_4, self.btnColor_6)
        MainWindow.setTabOrder(self.btnColor_6, self.btnColor_9)
        MainWindow.setTabOrder(self.btnColor_9, self.btnColor_11)
        MainWindow.setTabOrder(self.btnColor_11, self.btnColor_13)
        MainWindow.setTabOrder(self.btnColor_13, self.btnColor_5)
        MainWindow.setTabOrder(self.btnColor_5, self.txtHeroPermissions)
        MainWindow.setTabOrder(self.txtHeroPermissions, self.btnColor_7)
        MainWindow.setTabOrder(self.btnColor_7, self.btnColor_8)
        MainWindow.setTabOrder(self.btnColor_8, self.TabbedLayout)
        MainWindow.setTabOrder(self.TabbedLayout, self.btnColor_10)
        MainWindow.setTabOrder(self.btnColor_10, self.btnColor_3)
        MainWindow.setTabOrder(self.btnColor_3, self.btnColor_12)
        MainWindow.setTabOrder(self.btnColor_12, self.btnColor_14)
        MainWindow.setTabOrder(self.btnColor_14, self.btnColor_15)
        MainWindow.setTabOrder(self.btnColor_15, self.btnColor_16)
        MainWindow.setTabOrder(self.btnColor_16, self.btnColor_17)
        MainWindow.setTabOrder(self.btnColor_17, self.btnColor_18)
        MainWindow.setTabOrder(self.btnColor_18, self.btnColor_19)
        MainWindow.setTabOrder(self.btnColor_19, self.btnColor_20)
        MainWindow.setTabOrder(self.btnColor_20, self.btnColor_21)
        MainWindow.setTabOrder(self.btnColor_21, self.btnColor_22)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Hero Buddy 1.0", None))
        self.lblHeroesName.setText(_translate("MainWindow", "Heroes Name:", None))
        self.txtHeroesName.setToolTip(_translate("MainWindow", "<html><head/><body><p>What is the name of your Hero going to be? Don\'t include spaces. </p></body></html>", None))
        self.checkBoxOP.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set to True if your Hero requires OP. Generally if your hero is Invincible or uses features like Creative Mode.</p></body></html>", None))
        self.checkBoxOP.setText(_translate("MainWindow", "True", None))
        self.lblOP.setText(_translate("MainWindow", "Is Hero OP?", None))
        self.lblSpeech.setText(_translate("MainWindow", "Heroes Speech:", None))
        self.txtSpeech.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is what your Hero says when using the command /buff. Usually your characters famous tag line.</p></body></html>", None))
        self.lblFancyName.setText(_translate("MainWindow", "Heroes Fancy Name:", None))
        self.txtHeroesFancyName.setToolTip(_translate("MainWindow", "<html><head/><body><p>How will the name of your Hero appear in-game such as chat? You can use color codes to format the name, and you can use spaces.</p></body></html>", None))
        self.txtChatColor.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the color that the Heroes chat will appear as. Use the color codes found on the color codes page</p></body></html>", None))
        self.txtChatColor.setPlainText(_translate("MainWindow", "&0", None))
        self.lblChatColor.setText(_translate("MainWindow", "Chat Color: (Suffix)", None))
        self.lblTrails.setText(_translate("MainWindow", "Trails:", None))
        self.listTrails.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the Trail Permissions that your Super Hero will have access too. Example: Smoke, Wings, etc.</p></body></html>", None))
        self.listTrails.setSortingEnabled(False)
        self.lblOptional.setText(_translate("MainWindow", "(optional) Generally not Used", None))
        self.lblPowers.setText(_translate("MainWindow", "Powers:", None))
        self.txtPowers.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is the list of powers that are displayed for your hero when the player types the command /powers</p></body></html>", None))
        self.btnLoadPowersExample.setText(_translate("MainWindow", "Load Example", None))
        self.lblBuffs.setText(_translate("MainWindow", "Buffs:", None))
        self.txtBuffs.setToolTip(_translate("MainWindow", "<html><head/><body><p>This section gives the players special effects and/or items. See examples</p></body></html>", None))
        self.btnLoadBuffsExample.setText(_translate("MainWindow", "Load Example", None))
        self.lblYourHero.setText(_translate("MainWindow", "Your Hero", None))
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabCoreDetails), _translate("MainWindow", "Hero Details", None))
        self.lblPlayerName.setText(_translate("MainWindow", "Minecraft Player Name:", None))
        self.txtPlayerName.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter the Player Name you use in Minecraft</p></body></html>", None))
        self.btnUsePlayerName.setText(_translate("MainWindow", "use", None))
        self.txtInfoPlayerName.setToolTip(_translate("MainWindow", "<html><head/><body><p>The PlayerName you have used</p></body></html>", None))
        self.lblInfoPlayerName.setText(_translate("MainWindow", "Player Name:", None))
        self.txtInfoSignature.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Player\'s Texture Signature</p></body></html>", None))
        self.lblInfoSignature.setText(_translate("MainWindow", "Signature:", None))
        self.lblInfoUUID.setText(_translate("MainWindow", "UUID:", None))
        self.txtInfoValue.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Player\'s Texture Value</p></body></html>", None))
        self.txtInfoUUID.setToolTip(_translate("MainWindow", "<html><head/><body><p>The Player\'s UUID</p></body></html>", None))
        self.lblInfoValue.setText(_translate("MainWindow", "Value:", None))
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabPlayerDetails), _translate("MainWindow", "Your Player Info", None))
        self.lblBukkitCodeK.setText(_translate("MainWindow", "&k Obfuscated", None))
        self.lblBukkitCodeL.setText(_translate("MainWindow", "&l Bold", None))
        self.lblBukkitCodeM.setText(_translate("MainWindow", "&m Strikethrough", None))
        self.lblBukkitCodeN.setText(_translate("MainWindow", "&n Underline", None))
        self.lblBukkitCodeO.setText(_translate("MainWindow", "&o Italic", None))
        self.lblBukkitCodeR.setText(_translate("MainWindow", "&r Reset", None))
        self.lblScratchPad.setText(_translate("MainWindow", "Scratch Pad:", None))
        self.btnCloneToHeroName.setText(_translate("MainWindow", "Clone to Heroes Fancy Name", None))
        self.btnCloneToHeroesSpeech.setText(_translate("MainWindow", "Clone to Heroes Speech", None))
        self.btnClearScratchPad.setText(_translate("MainWindow", "Clear", None))
        self.btnCloneToHeroesChatColor.setText(_translate("MainWindow", "Clone to Chat Color", None))
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabColorCodes), _translate("MainWindow", "Color Codes", None))
        self.txtHeroPermissions.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enter the permissions that your hero will have. Use one permission per line. To take away a permission for your hero, use a hypen before the permission name such as -permission.name</p></body></html>", None))
        self.lblHeroCustomPermissions.setText(_translate("MainWindow", "Custom Permissions:", None))
        self.lblAvailablePermissions.setText(_translate("MainWindow", "Available Permissions:", None))
        self.lblCustomPermissionsHelp.setText(_translate("MainWindow", "Write your own permissions in the box below. One for each line. Use a hyphen \'-\' to disable a permission. Used for things such as fall damage.", None))
        self.lblAvailablePermissionsHelp.setText(_translate("MainWindow", "Select which permissions you\'d like to use from the existing ones available to you. If you need to modify a permission then manually type out the permission in the left box.", None))
        self.lblPermissionsInfo.setText(_translate("MainWindow", "When you create your hero using the \'Build\' tab; both the permissions you have manually entered in the Custom Permissions box and the Permissions you have selected in the Available Permissions box will be added to your hero.", None))
        self.listPermissions.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select which permissions you\'d like your Super Hero to have. You can select multiple permissions.</p></body></html>", None))
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabPermissions), _translate("MainWindow", "Hero Permissions", None))
        self.listEnchantments.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the Trail Permissions that your Super Hero will have access too. Example: Smoke, Wings, etc.</p></body></html>", None))
        self.listEnchantments.setSortingEnabled(False)
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabEnchantments), _translate("MainWindow", "Enchantments", None))
        self.listEffects.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the Trail Permissions that your Super Hero will have access too. Example: Smoke, Wings, etc.</p></body></html>", None))
        self.listEffects.setSortingEnabled(False)
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabEffects), _translate("MainWindow", "Effects", None))
        self.listBlocks.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the Trail Permissions that your Super Hero will have access too. Example: Smoke, Wings, etc.</p></body></html>", None))
        self.listBlocks.setSortingEnabled(False)
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabBlockIDs), _translate("MainWindow", "Block && Item ID\'s", None))
        self.btnCreate.setToolTip(_translate("MainWindow", "<html><head/><body><p>Used to create your hero and generate the neccassary files when you are finished.</p></body></html>", None))
        self.btnCreate.setText(_translate("MainWindow", "Create Hero Files", None))
        self.TabbedLayout.setTabText(self.TabbedLayout.indexOf(self.tabBuild), _translate("MainWindow", "Build", None))
        self.lblHeroBuddy.setText(_translate("MainWindow", "Hero Buddy", None))

