@plr = player()


@hero = associative_array(
            'name': 'POOO',
            'class': 'baglickers',
            'sig': 'dsk5z+gjZinAK7rzLL1nhMXIa5zsv2Z0QtAcwmnIJQ3WCLVT21GdB3ZHjoU/M6JTNbXTgT6mlLRbFwZIR/pHG+PQreiskXpiYclQKRaj6Cc1t5Ef+5GUJiOkWnetn2x8ReEN7Vsuh34KT8qFFTA5eF6daiMTmH6fSt2dL8Iy0kjkCklG4evJugXIn6UyXKiuI5VAMnty62pqFdh8doEu8Is1k4pUgT2fwUzeeQMxFhA1++g8MUkNJdPZoJSoOVMvwuWao7m+Np0HB31855twoDDIesmQQhb32rZJbt/9yQ79g3pFzqvIppeD0mYryV13vWwXZCNodATzRLOnXQCP/s1mUTybYl0iH1IbXq0JWIUMQpGsB0nL1vc4P0tPyj/rBoBkgF/LQ5bohU8BDF5bCJkq8zaiWL9upCvC3tQ/dYknBrFLvs3Jlawwz1G3mcbV9kzvcDyyAFAr6//8lS3e69Wix/4K/tXKuwaBnrr5JeLKEQ9p3MRLdYZt5qdv3ysBK9DSckpJJjz9nQUnpkNmuSvYRIKWiS0rJ1EENfOXuTR+XnQOXjjWfSLfvEbsOv9A3oe4LuuO/DfEDmHiNRSCEWKCi2TXZrqHZSea+Kuv+0B+wFa9wU7kjUxvf8NIk6fJzBoPThFsESDkUBvVRSaGk1xR3hkgZyGA5AQPLdrUUig=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE3MDM0ODYzOTcsInByb2ZpbGVJZCI6ImNiODcxZjg2OTRlNTRiZjNhNzhlNDJmNzNjMjIxNWM0IiwicHJvZmlsZU5hbWUiOiJ4U3A0cmt6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYjAzOTlmMTJhMjZmYjQyNWNmMTZhZTA1OTYyYzdjNTFiNWY0Mzg1N2Y0Mjc0Y2ZmY2YxYzY1NmNmMSJ9fX0=',
            'trail': 'trail.angry',
            'op': 'true',
            'speech': "WOW!!!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7m&8a&7n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"
            )
)
