@plr = player()


@hero = associative_array(
            'name': 'DickLicker',
            'class': 'dickballs',
            'sig': 'YwP2PETHSJeOlarMvTpYgQXThzlW8QvjQO1dD7qEgHkbmqoNZYwDOVyAv6EFFKqvCUbjRmW/oIapR6auAvbXywF0RcCn92yAF+ZBBnNhUa9YQS+Ef6bNeYST4OH7Bamj6uJSZQR+gjCtSaWsJXFA5H655mvVIhGHM3vCXCbDtl7JLG9QPyJNBEl5fIiMn+jz2Qc0o9l3dPrwy81hWmFSfqSTlw+wUJa989B4K5IayfPXvrmkSmVVv89SoGOT6w3pf7IPfGue7jW0BLayB1bGdIxExbQecTJvXeUyIJs1ENf4LlXf7OjIKDW5WsPGR9lW4Y5XgZMVw4wFylcNX4jXzrBwz1K9Nmajcb8Q/kNv6B53zUa31GvIezNd0AseI2f/pkrpceuh2daweCfA+tpcQaazP2EiJTQn4WFycCvsXDyZhFbT2woH8w3cz9pGHvSeKKahEjN2BHax0tW8joFns6hY28a6Az6niPub5DjQfpR46ffQjb3chAL7YQWm5Ea9UNjsztc3A7oXe1gyDwWjmT03QBKgfOKN6FnL4nXp0pygQHW20rocSca5ET5JrZsycZlRBgn0ktJlPfFC0Iy19W3/W3HGDG1PvLTsifeEehBypZDIX/6IhNMjCnjw2GEK1SOMkRmXA29fw4+2I3dt4jxoMXGEj0rVe+ZxoKdfUWU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE2ODMwNzQ4MjksInByb2ZpbGVJZCI6ImNiODcxZjg2OTRlNTRiZjNhNzhlNDJmNzNjMjIxNWM0IiwicHJvZmlsZU5hbWUiOiJ4U3A0cmt6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYjAzOTlmMTJhMjZmYjQyNWNmMTZhZTA1OTYyYzdjNTFiNWY0Mzg1N2Y0Mjc0Y2ZmY2YxYzY1NmNmMSJ9fX0=',
            'trail': '<trail>',
            'op': 'false',
            'speech': "Balls to the Wall!!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7m&8a&7n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"
            )
)
