@plr = player()


@hero = associative_array(
            'name': 'Fancy Bitch',
            'class': 'dicklicker',
            'sig': 'S0ov93rRwLfUZkxowi/cCqB8gPedF7kQ4W3TzWdO9dBmEzUYAOWUJw8rDqZPO/dyjAlNDgpB3/q8G3NMZytSgvDd+zglPqn7ilyYlUrirdng6ixG9hHPyopi18NukC7yB/sMyQC0szvmdPCAk7tsl79ai5uBMs4Paim3tCKXBpIckHABpKsUwXO9TMhn8TgFljAt9VlQAWNo5uKqELoAwDc7EuMDKDp/PcPi2RquUVydb73jHIm9Ncz63W585id5Z0/QLSTRP4uAWZWO8BN0QNuy8AvLM9KeClcj1uvdiHtBs0ZCxhRUbztYtpTW3fq7J8ZRL0tPhhJUnKcOQnOvhqnA3hnxEAxuDnAHhAv0XdKZFvchSI+leYwGlHZhVLAO4i/rS0dLcofnLNW8VyA8gupoS14WR7GRU0bSRE7uM+ZnEPgM8cSBKDfR0IzoUXqJtlqYmRtuA+jRosYM7nL0UKV0eqRGvVKnzcNun3xrR/NhFRfCAMq+1bmbV/9mN8CL190KKdFuCzHUlXQD/Ak8aJAb2IqDAVyVr04CQGSNFV190k+I770Xbx+qqGAkyKO0Pdtw7Ij0twbQ2EtHL/TWABoePe4FjUoSqALy6fLd2RUgK3GIRAemVY+LRArp5cHoUdohtdTXQ/OAqyZL6anmQwZ9xw3vuVFb1cf6FmqX09U=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE3MDI2MDIzNzMsInByb2ZpbGVJZCI6ImNiODcxZjg2OTRlNTRiZjNhNzhlNDJmNzNjMjIxNWM0IiwicHJvZmlsZU5hbWUiOiJ4U3A0cmt6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYjAzOTlmMTJhMjZmYjQyNWNmMTZhZTA1OTYyYzdjNTFiNWY0Mzg1N2Y0Mjc0Y2ZmY2YxYzY1NmNmMSJ9fX0=',
            'trail': 'trail.angry, ',
            'op': 'false',
            'speech': "Wow!!!!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7m&8a&7n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"
            )
)
