@plr = player()


@hero = associative_array(
            'name': '&1&kD&9ickbate',
            'class': 'dickbait',
            'sig': 'hyZdnFU2nDdGGurappF3f0GBiz9KkqdPEkUseOxsCjqMgAdUkC+bXDtZ34mEl4l16yfdlsBWJBQ4vc2r682aCZmqzce4NqPn7t5ydJdrMrhD8QtWkz6zSFqMKWz3V1eZ7g+ybNL9XRm75zhBdMM+Kc2OhaR38Ik+iPf8r8OSo7+CItvMWunusMJ9CP7F+XMn2AqnWGqg+iChUPuRa+bOQ+lNnAqrzqMKMgFxMkT9Fyo1qEmnzuPZXlkCWHkkSUgsOLNoNM3NQxgGm9jL61KOZrg5KfNa+rP67D9BUH/2K2SVwI3vMFNJHUsHfh013Q2hzwY/HW/oaMtqdeVcIXbXnCHm+T32U+8eLAlN/04ktb85Yf+hKEJ6W4RSkAb49pCZTAIC4ZZ39kwxDTSONya1FtkRuaggnDTLbQCyO3tvxQQR7aK6d10hmOHadgK/YcYtKrMIKTE+Xkb0PGqpb59O0x3CNVPCWH9gMosFt9vKDtYL8p+E6whlFRBTvCw+YvWcBehjEZfhDrzN7hE9jYj4oFUdLdcI8JLocSSFl5eB3BR6e5Td+DZ8fkRYZ0KeZRikx913vlncTMXRBpU8GOnpKQcIzrCGeAvI+MWGDrWO826Kd0wqdVcnii17CFtih69k9xSePo0oUyPPGbRobtQB8bMbNNx8MV47S6ON0yGw3gE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE2Nzk5ODU2OTIsInByb2ZpbGVJZCI6ImNiODcxZjg2OTRlNTRiZjNhNzhlNDJmNzNjMjIxNWM0IiwicHJvZmlsZU5hbWUiOiJ4U3A0cmt6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYjAzOTlmMTJhMjZmYjQyNWNmMTZhZTA1OTYyYzdjNTFiNWY0Mzg1N2Y0Mjc0Y2ZmY2YxYzY1NmNmMSJ9fX0=',
            'trail': '<trail>',
            'op': 'true',
            'speech': "Eat my balls!",
            'powers': array(
                <powers>
            ),
            'buffs': array(
                <buffs>
            )
)
