@plr = player()


@hero = associative_array(
            'name': 'god',
            'class': 'god',
            'sig': 'vqAvkxGw7kd4kV99952GAKUDHhxT5KYE5PMo2UvGhG7YYYEYV8rISMLlhtB8rMzkzRF58KmTH2GTyZYUZBEsz+6WJTRlP2NztU2G6JkDyjVlmJl0svCNX2JdF9ldGZqUdRzj7khXyABu+ndPkGiSiYyUqy+STGy8x5X9sIsgoGQhnVKPR3wVoN55P01q3vywlgDn3HKi7gNgR7EOxVDFOCvROmvsuwLvSJPH/IbUUz7qVxgL6YcTqCh//jFkuT3lZ54SePkmkVudyCko/EoieaEEkqI16nzGTCFTr7HWWoMqA81mtNK09EEbXtCGuTvMdrweoVzPL9DkYxKFQCYUjwb6Nc489x+4kFxlrdCAu1q+yU0Ghk5lkTro1JdvfD9Fbx0tGRN5lHj9kX3QJFu12Qr0W1kmZpIY5Keq5eOrbesDB2scX1M4K5TnK/+qX7pshR389UCPsOiurvulQsWCtep/YKnf0tdgZWcVoCMiB3ag6YI/x0VTVr/jaTgnOwViaEMYATUQ+RJmDfVrxH2jjop6O9l9PLcnYv96eMVvQ2P2egouWwUj7CIj0chmFn6xDK4piEcioJmI2H612NygFGrkFV6laZQz3mYP+n6m5063Q7B+X8ltS+ExsiKHvodPXmt47/24OoH2E32NOIEIJ1bRFLT72pzWkYA2zUqJKvQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE2ODM2NDg2NzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85OGVkOGUxOTkwZDM3ZWQ5NTI2MDcyYzY0NDhkM2EyN2RiZTQ2YzJkYjkxZjVjZWRhZDliYTNjNDk3NWYxYjIifX19',
            'trail': '<trail>',
            'op': 'true',
            'speech': "Fingle Bitch",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7m&8a&7n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"
            )
)
