@plr = player()


@hero = associative_array(
            'name': 'Jaxon',
            'class': 'jax',
            'sig': 'wM4FfLeCDNIa/4/IY/opifjeZ5iUooh37MsKKzXq0trV9mlPqyiNPmu6IOPcNF1z5hGmZSomhega6o9mLgAe6/v2zbuSDugb8pgJ68B4J0njDN+lfgxa2WXp2eEOlku97546uxUFrmnGM1mj62HxEMUuKfHqxT6c48XUq/Z616Ju8O2eAOrbj8f3rkjCk+06Q8DRVRrS8IUQMTBpb/1b2iZ160dy7Cnsjg1/wRIqYWmS5+0LmeX8PCqWsa+shdnNXJHVZDcePdziGRzAdR8ks2zXE9E0NhMTV/9cOiO4YBZpqMfG1dXrUxBPnU5NYbLDrKC6eo5yJEBvMtoDz0PYsIMjbatJgoB4A7zwUOvH3uVREAqKqeYSmp68x0zqu1dOm0EfyJXmHffsMAqhI7adoTtZPu8IsO/82o2WzWMZLsxGMwCrPJaoFAEeSrJ8vNuupaYlPEgF1Y2AMzCdvQjJtysaIVgd2qVFm0BKbUVV/KnRvIi04aSw+FHe53v7Hi6osO4Czf+UQQzPprfXsl8ybhe/+H30xheuEpLzKIGSC3XWvoEREFlAGSev/V0WyZgocWzXKJm8/kVVWAa8f3SpkeMFZ7ULUq2rN1zCz31jqT6VUefFIItPRiEdgLYSh2Bgv5wWmAF5dQ1l8SitWuJdanS89motxq3hyK/oEWVDUv8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE2ODMzNDc4MzksInByb2ZpbGVJZCI6ImNiODcxZjg2OTRlNTRiZjNhNzhlNDJmNzNjMjIxNWM0IiwicHJvZmlsZU5hbWUiOiJ4U3A0cmt6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYjAzOTlmMTJhMjZmYjQyNWNmMTZhZTA1OTYyYzdjNTFiNWY0Mzg1N2Y0Mjc0Y2ZmY2YxYzY1NmNmMSJ9fX0=',
            'trail': '<trail>',
            'op': 'false',
            'speech': "Fucker",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true"
            )
)
