@plr = player()


@hero = associative_array(
            'name': '<heroname>',
            'class': '<classname>',
            'sig': '<signature>',
            'val': '<value>',
            'trail': '<trail>',
            'op': '<op>',
            'speech': "<speech>",
            'powers': array(
                <powers>
            ),
            'buffs': array(
                <buffs>
            )
)